### ISSUE TITLE
Missing units and background-colors

### ISSUE THREAD

**Issue by patrikholcak** [csshat/language-scss-compass#1]
In CSS:

```
/* Style for Shape 373 copy 12 */
width: 21.03125px;
height: 20px;
background-color: #D5D5D5;
```

In SCSS with compass:

```
// Style for Shape 373 copy 12
width: 21.03125;
height: 20;
background-color: ;
```

**Comment by marekhrabe** [comment]
Also inspect the wtf rounding in width. It shouln't happen AFAIK :crying_cat_face: 

Update: I suspect `octopus-helpers` dependency not to be installed, because they are used to normalize these values. Maybe we can add them as a dependency of main module, so templates can fallback to them.
